inherits: configs/emodb.yaml

model:
  name: WavLM_Att
  wavlm_name: microsoft/wavlm-base
  freeze_wavlm: true
  mfcc_dim: 40
  mfcc_hidden_size: 256
  mfcc_num_layers: 1
  spectrogram_feature_dim: 512
  attention_dim: 256
  fusion_mode: co_attention
  fusion_dim: 512
  mha_num_heads: 4
  classifier_hidden_dim: 256
  dropout: 0.5
  num_classes: 7
